# Travis Auto Builder for Project Gabriel Ver 1
language: rust
os:
  - linux
  - windows
  - osx
before_cache:
  - rm -rf "$TRAVIS_HOME/.cargo/registry/src"
cache: cargo
install:
  - git clone https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@gitlab.com/theprojectgabriel/core-builds.git >/dev/null;
  - git clone https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@gitlab.com/theprojectgabriel/core.git >/dev/null;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then rustup target add i686-unknown-linux-musl; sudo apt-get install musl-tools clang; export target="i686-unknown-linux-musl"; export TARGET_CC=clang; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then rustup target add i686-pc-windows-msvc; export target="i686-pc-windows-msvc"; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then rustup target add x86_64-apple-darwin; export target="x86_64-apple-darwin"; fi
script:
  - cd core;
  - cargo test && cargo build --target ${target} && cargo build --target ${target} --release && for i in "client" "libshared.rlib" "manager" "proxy" "server"; do for j in "debug" "release"; do cp target/${target}/${j}/${i} ../core-builds/${i}-${target}-${j}; done; done;
  - export message=$(git log -1 --pretty=%B) && export git_commit_id=$(git rev-parse --short HEAD);
  - cd ..;
after_script:
  - cd core-builds;
  - git config --local user.name "Project Gabriel";
  - git config --local user.email "gabrielproject@protonmail.com";
  - git pull;
  - git add *;
  - git commit -m "Travis CI Build";
  - git remote set-url origin https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@gitlab.com/theprojectgabriel/core-builds.git >/dev/null;
  - git push -u origin master;
  - cd ..;
  - bash ./telegram.sh "${message}" "${git_commit_id}";
  - rm -rf core-builds core;
